version: '3.8'

services:
  music-genre-classifier-core:
    build: .
    ports:
      - "5000:5000"
    environment:
      - ENVIRONMENT=production
      - PORT=5000
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
