services:
  - type: web
    name: nebula-ai-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    branch: main
    plan: free
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: "18"
      - key: FLASK_API_URL
        value: "http://localhost:5004"  # Update this to your Flask backend URL
